name: EthornRaces
version: 1.0.0
description: Races manager

author: CIad

main: fr.ethorn.races.Main

commands:
  caste:
    description: Liste de toutes les classe disponible pour toute les races
  race:
    description: Liste de toutes les races disponibles sur le serveur 
  casteJoin:
    description: le joueur pourra rejoindre une castes avec cette commande